name: "Helm Push"
description: "Perform Helm Push"
inputs:
  appid:
    description: "Application ID"
    required: true
  orgid:
    description: "Organization ID"
    required: true
  buid:
    description: "Build ID"
    required: true
  chart-archive:
    description: "The .tgz file name"
    required: true
  package:
    description: "Package path (repo-name/helm/chart-name)"
    required: true
  version:
    description: "The final version of the chart (calculated or override)"
    required: true
  github-token:
    description: "GitHub Token for authenticating with GHCR"
    required: false
    default: ${{ github.token }}
  repository:
    description: "Repository name"
    required: false
    default: "platform"
  dockerhub-username:
    description: "Docker Hub Username"
    required: true
  dockerhub-token:
    description: "Docker Hub Token or Password"
    required: true

runs:
  using: "composite"
  steps:
    - name: Push Helm Chart to Docker Hub
      id: push-to-dockerhub
      if: ${{ github.event_name == 'push' }}
      shell: bash
      env:
        ORGID: ${{ inputs.orgid }}
        BUID: ${{ inputs.buid }}
        APPID: ${{ inputs.appid }}
        CHART_ARCHIVE: ${{ inputs.chart-archive }}
        PACKAGE: ${{ inputs.package }}
        VERSION: ${{ inputs.version }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        REPOSITORY: ${{ inputs.repository }}
        DOCKERHUB_USERNAME: ${{ inputs.dockerhub-username }}
        DOCKERHUB_TOKEN: ${{ inputs.dockerhub-token }}
      run: |
        chmod +x ${{ github.action_path }}/scripts/push_helm_to_dockerhub.sh
        ${{ github.action_path }}/scripts/push_helm_to_dockerhub.sh

    - name: Cleanup non-main branches from Docker Hub
      id: cleanup-non-main-dockerhub
      if: ${{ github.event_name == 'pull_request' }}
      shell: bash
      env:
        ORGID: ${{ inputs.orgid }}
        BUID: ${{ inputs.buid }}
        APPID: ${{ inputs.appid }}
        CHART_ARCHIVE: ${{ inputs.chart-archive }}
        PACKAGE: ${{ inputs.package }}
        VERSION: ${{ inputs.version }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        REPOSITORY: ${{ inputs.repository }}
        BRANCH_NAME: ${{ github.head_ref }}
        DOCKERHUB_USERNAME: ${{ inputs.dockerhub-username }}
        DOCKERHUB_TOKEN: ${{ inputs.dockerhub-token }}
      run: |
        chmod +x ${{ github.action_path }}/scripts/cleanup_helm_from_dockerhub.sh
        ${{ github.action_path }}/scripts/cleanup_helm_from_dockerhub.sh
